name=SF_PID
version=1.0.0
author=Saul Fernandes
maintainer=Saul Fernandes <saul-jazz@hotmail.com>
sentence=Um controlador PID rápido com opção de aquecimento e refrigeração e autotune integrado.
paragraph=Baseada na QuickPID, otimizada para controle termico de equipamentos laboratoriais.
category=Signal Input/Output
architectures=*
